package environment

const (
	DB_MAIN_NAME         = "main"
	ENV_DB_MAIN_USER     = "ENV_DB_MAIN_USER"
	ENV_DB_MAIN_HOST     = "ENV_DB_MAIN_HOST"
	ENV_DB_MAIN_PASSWORD = "ENV_DB_MAIN_PASSWORD"

	DB_READ_NAME         = "read"
	ENV_DB_READ_USER     = "ENV_DB_READ_USER"
	ENV_DB_READ_HOST     = "ENV_DB_READ_HOST"
	ENV_DB_READ_PASSWORD = "ENV_DB_READ_PASSWORD"
)
